export const FETCH_USER_PERMISSIONS = "FETCH_USER_PERMISSIONS";
export const FETCH_USER_DEPARTMENTS = "FETCH_USER_DEPARTMENTS";
export const FETCH_USER_SUBORDINATES = "FETCH_USER_SUBORDINATES";
export const FETCH_PERSON_PROFILE = "FETCH_PERSON_PROFILE";
export const FETCH_ALL_PERSONS = "FETCH_ALL_PERSONS";

export const SET_USER_PERMISSIONS = "SET_USER_PERMISSIONS";
export const SET_USER_DEPARTMENTS = "SET_USER_DEPARTMENTS";
export const SET_USER_SUBORDINATES = "SET_USER_SUBORDINATES";
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const SET_SELECTED_USER_PROFILE = "SET_SELECTED_USER_PROFILE";
export const SET_ALL_PERSONS = "SET_ALL_PERSONS";




export const API = "API";
export const API_START = "API_START";
export const API_END = "API_END";
export const ACCESS_DENIED = "ACCESS_DENIED";
export const API_ERROR = "API_ERROR";
